# Generated by Django 2.2.12 on 2020-04-14 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Waiting for paying'), ('canceled', 'Cancled order'), ('unsuccessful', 'Unsuccessfull payment'), ('successful', 'Successful payment')], default='pending', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShipPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(datetime.timedelta(28), '1 month'), (datetime.timedelta(84), '3 month'), (datetime.timedelta(168), '6 month'), (datetime.timedelta(336), '1 year')], default=datetime.timedelta(28), max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
