# Generated by Django 2.2.12 on 2020-04-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('membership', '0002_membershipplans_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiporder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerUser'),
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.MemberShipPlans'),
        ),
    ]
