# Generated by Django 2.2.12 on 2020-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20200414_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplans',
            name='type',
            field=models.IntegerField(choices=[(1, '1 month'), (3, '3 month'), (6, '6 month'), (12, '1 year')], default=1, max_length=255),
        ),
    ]
