# Generated by Django 2.2.12 on 2020-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20200414_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiporder',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='membershiporder',
            old_name='end_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
