# Generated by Django 2.2.12 on 2020-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20200414_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiporder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
