# Generated by Django 2.2.12 on 2020-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200414_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplans',
            name='type',
            field=models.IntegerField(choices=[(4, '1 month'), (12, '3 month'), (24, '6 month'), (48, '1 year')], default=4),
        ),
    ]
