# Generated by Django 2.2.12 on 2020-04-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200415_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
