# Generated by Django 2.2.12 on 2020-04-13 17:38

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to=content.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='file',
            name='price',
            field=models.BigIntegerField(verbose_name=content.models.content_file_name),
        ),
    ]
