# Generated by Django 2.2.12 on 2020-04-16 19:31

import content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200414_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to=content.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'avi', 'mp4', 'mp3'])]),
        ),
    ]
